"""All models

Revision ID: 3b51bc0b0485
Revises: 
Create Date: 2025-04-12 20:30:58.766200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b51bc0b0485'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'presentation', ['code'])
    op.create_unique_constraint(None, 'room', ['code'])
    op.create_unique_constraint(None, 'user', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'room', type_='unique')
    op.drop_constraint(None, 'presentation', type_='unique')
    # ### end Alembic commands ###
