"""Add refresh token to user

Revision ID: 86dbc00b6978
Revises: ad1e292f1911
Create Date: 2025-04-07 20:13:44.135082

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86dbc00b6978"
down_revision: Union[str, None] = "ad1e292f1911"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("refresh_token", sa.String(length=300), nullable=True)
    )
    op.create_unique_constraint(None, "users", ["code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "refresh_token")
    # ### end Alembic commands ###
