"""ADD: room and presentation with many to many

Revision ID: 91f48cec9e24
Revises: aaad97f941eb
Create Date: 2025-04-09 00:30:59.942686

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "91f48cec9e24"
down_revision: Union[str, None] = "aaad97f941eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "room", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "room", type_="unique")
    # ### end Alembic commands ###
